using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using MTA.Client;
using MTA.Game.Attacking;
using MTA.Network.GamePackets;

namespace MTA.Effect
{
    public class effectx
    {

        #region All Effects
        public static void cortege(GameState client) { client.Entity.Update(_String.Effect, "cortege", true); }
        public static void the_wes_03low(GameState client) { client.Entity.Update(_String.Effect, "the_wes_03low", true); }
        public static void the_wes_04hig(GameState client) { client.Entity.Update(_String.Effect, "the_wes_04hig", true); }
        public static void the_wes_04lowd(GameState client) { client.Entity.Update(_String.Effect, "the_wes_04low", true); }
        public static void the_wes_05hig(GameState client) { client.Entity.Update(_String.Effect, "the_wes_05hig", true); }
        public static void the_wes_05low(GameState client) { client.Entity.Update(_String.Effect, "the_wes_05low", true); }
        public static void hdhththt(GameState client) { client.Entity.Update(_String.Effect, "900269", true); }
        public static void hoo_01_hig(GameState client) { client.Entity.Update(_String.Effect, "hoo_01_hig", true); }
        public static void hoo_01_low(GameState client) { client.Entity.Update(_String.Effect, "hoo_01_low", true); }
        public static void hoo_02_hig(GameState client) { client.Entity.Update(_String.Effect, "hoo_02_hig", true); }
        public static void hoo_02_low(GameState client) { client.Entity.Update(_String.Effect, "hoo_02_low", true); }
        public static void hoo_03_hig(GameState client) { client.Entity.Update(_String.Effect, "hoo_03_hig", true); }
        public static void Magicflying1(GameState client) { client.Entity.Update(_String.Effect, "Magicflying1-1", true); }
        public static void Magicflying12(GameState client) { client.Entity.Update(_String.Effect, "Magicflying1-2", true); }
        public static void Magicflying21(GameState client) { client.Entity.Update(_String.Effect, "Magicflying2-1", true); }
        public static void Magicflying22(GameState client) { client.Entity.Update(_String.Effect, "Magicflying2-2", true); }
        public static void Magicflying31(GameState client) { client.Entity.Update(_String.Effect, "Magicflying3-1", true); }
        public static void Magicflying32(GameState client) { client.Entity.Update(_String.Effect, "Magicflying3-2", true); }
        public static void pir_roe_01hig(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_01hig", true); }
        public static void pir_roe_01low(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_01low", true); }
        public static void pir_roe_02hig(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_02hig", true); }
        public static void pir_roe_02low(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_02low", true); }
        public static void pir_roe_03hig(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_03hig", true); }
        public static void pir_roe_03low(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_03low", true); }
        public static void pir_roe_04hig(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_04hig", true); }
        public static void pir_roe_04low(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_04low", true); }
        public static void pir_roe_05hig(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_05hig", true); }
        public static void pir_roe_05low(GameState client) { client.Entity.Update(_String.Effect, "pir_roe_05low", true); }
        public static void the_wes_01hig(GameState client) { client.Entity.Update(_String.Effect, "the_wes_01hig", true); }
        public static void the_wes_01low(GameState client) { client.Entity.Update(_String.Effect, "the_wes_01low", true); }
        public static void the_wes_02hig(GameState client) { client.Entity.Update(_String.Effect, "the_wes_02hig", true); }
        public static void the_wes_02low(GameState client) { client.Entity.Update(_String.Effect, "the_wes_02low", true); }
        public static void the_wes_03hig(GameState client) { client.Entity.Update(_String.Effect, "the_wes_03hig", true); }
        public static void MapleFores(GameState client) { client.Entity.Update(_String.Effect, "MapleFores", true); }
        public static void Market(GameState client) { client.Entity.Update(_String.Effect, "Market", true); }
        public static void monster(GameState client) { client.Entity.Update(_String.Effect, "monster", true); }
        public static void MoonSprin(GameState client) { client.Entity.Update(_String.Effect, "MoonSprin", true); }
        public static void n_Franko(GameState client) { client.Entity.Update(_String.Effect, "n-Franko", true); }
        public static void noconfirm(GameState client) { client.Entity.Update(_String.Effect, "noconfirm", true); }
        public static void other(GameState client) { client.Entity.Update(_String.Effect, "other", true); }
        public static void perfect(GameState client) { client.Entity.Update(_String.Effect, "perfect", true); }
        public static void PhoenixCity(GameState client) { client.Entity.Update(_String.Effect, "PhoenixCity", true); }
        public static void QiXingGao(GameState client) { client.Entity.Update(_String.Effect, "QiXingGao", true); }
        public static void ReedIsland(GameState client) { client.Entity.Update(_String.Effect, "ReedIsland", true); }
        public static void reif(GameState client) { client.Entity.Update(_String.Effect, "reif", true); }
        public static void role(GameState client) { client.Entity.Update(_String.Effect, "role", true); }
        public static void SanYangKai(GameState client) { client.Entity.Update(_String.Effect, "SanYangKai", true); }
        public static void scene(GameState client) { client.Entity.Update(_String.Effect, "scene", true); }
        public static void clewarbig(GameState client) { client.Entity.Update(_String.Effect, "clewarbig", true); }
        public static void clewarsma(GameState client) { client.Entity.Update(_String.Effect, "clewarsma", true); }
        public static void scene_FF(GameState client) { client.Entity.Update(_String.Effect, "scene-FF", true); }
        public static void ShiQuanShi(GameState client) { client.Entity.Update(_String.Effect, "ShiQuanShi", true); }
        public static void SiJiPingAn(GameState client) { client.Entity.Update(_String.Effect, "SiJiPingAn", true); }
        public static void skill(GameState client) { client.Entity.Update(_String.Effect, "skill", true); }
        public static void TwinCity(GameState client) { client.Entity.Update(_String.Effect, "TwinCity", true); }
        public static void WaterfallCa(GameState client) { client.Entity.Update(_String.Effect, "WaterfallCa", true); }
        public static void weapon(GameState client) { client.Entity.Update(_String.Effect, "weapon", true); }
        public static void WindPlain(GameState client) { client.Entity.Update(_String.Effect, "WindPlain", true); }
        public static void Wonderlan(GameState client) { client.Entity.Update(_String.Effect, "Wonderlan", true); }
        public static void swordcaromstart03(GameState client) { client.Entity.Update(_String.Effect, "swordcaromstart03", true); }
        public static void swordcaromstart04(GameState client) { client.Entity.Update(_String.Effect, "swordcaromstart04", true); }
        public static void swordcaromstart05(GameState client) { client.Entity.Update(_String.Effect, "swordcaromstart05", true); }
        public static void tal_att_flf(GameState client) { client.Entity.Update(_String.Effect, "tal_att_flf", true); }
        public static void Rab_Est_app5(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app5", true); }
        public static void Rab_Est_app6(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app6", true); }
        public static void Rab_Est_app7(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app7", true); }
        public static void Rab_Est_app8(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app8", true); }
        public static void sou_swo_sta(GameState client) { client.Entity.Update(_String.Effect, "sou_swo_sta", true); }
        public static void poisoncast05(GameState client) { client.Entity.Update(_String.Effect, "poisoncast05", true); }
        public static void poisonfog01(GameState client) { client.Entity.Update(_String.Effect, "poisonfog01", true); }
        public static void poisonfog02(GameState client) { client.Entity.Update(_String.Effect, "poisonfog02", true); }
        public static void poisonfog03(GameState client) { client.Entity.Update(_String.Effect, "poisonfog03", true); }
        public static void poisoncast(GameState client) { client.Entity.Update(_String.Effect, "poisoncast", true); }
        public static void die_paa_acc(GameState client) { client.Entity.Update(_String.Effect, "die_paa_acc", true); }
        public static void die_paa_ass(GameState client) { client.Entity.Update(_String.Effect, "die_paa_ass", true); }
        public static void dispersion(GameState client) { client.Entity.Update(_String.Effect, "dispersion", true); }
        public static void endurexp(GameState client) { client.Entity.Update(_String.Effect, "endurexp", true); }
        public static void Rab_Est_att(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_att", true); }
        public static void Rab_Est_app1(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app1", true); }
        public static void int_fir_acc(GameState client) { client.Entity.Update(_String.Effect, "int_fir_acc", true); }
        public static void int_fir_ass(GameState client) { client.Entity.Update(_String.Effect, "int_fir_ass", true); }
        public static void int_fir_muz(GameState client) { client.Entity.Update(_String.Effect, "int_fir_muz", true); }
        public static void KillerPattern(GameState client) { client.Entity.Update(_String.Effect, "KillerPattern", true); }
        public static void Thunderbolt(GameState client) { client.Entity.Update(_String.Effect, "Thunderbolt", true); }
        public static void ScapegoatSwitchOpen(GameState client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen", true); }
        public static void zf2_e129break_a(GameState client) { client.Entity.Update(_String.Effect, "zf2-e129break_a", true); }
        public static void endureXPwordq(GameState client) { client.Entity.Update(_String.Effect, "endureXPwordq", true); }
        public static void ScapegoatSwitchOpen02(GameState client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen02", true); }
        public static void zf2_e181(GameState client) { client.Entity.Update(_String.Effect, "zf2-e181", true); }
        public static void endureXPappear(GameState client) { client.Entity.Update(_String.Effect, "endureXPappear", true); }
        public static void endureXPattac(GameState client) { client.Entity.Update(_String.Effect, "endureXPattac", true); }
        public static void endureXPbing(GameState client) { client.Entity.Update(_String.Effect, "endureXPbing", true); }
        public static void Rab_Est_cyc0(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_cyc0", true); }
        public static void endureXPdeat(GameState client) { client.Entity.Update(_String.Effect, "endureXPdeat", true); }
        public static void RapidReplace(GameState client) { client.Entity.Update(_String.Effect, "RapidReplace", true); }
        public static void endureXPdisa(GameState client) { client.Entity.Update(_String.Effect, "endureXPdisa", true); }
        public static void poisonparoxy(GameState client) { client.Entity.Update(_String.Effect, "poisonparoxy", true); }
        public static void endureXPscre(GameState client) { client.Entity.Update(_String.Effect, "endureXPscre", true); }
        public static void replaceappear(GameState client) { client.Entity.Update(_String.Effect, "replaceappear", true); }
        public static void endureXPstate(GameState client) { client.Entity.Update(_String.Effect, "endureXPstate", true); }
        public static void endureXPswor(GameState client) { client.Entity.Update(_String.Effect, "endureXPswor", true); }
        public static void endureXPwor(GameState client) { client.Entity.Update(_String.Effect, "endureXPwor", true); }
        public static void replacedisappe(GameState client) { client.Entity.Update(_String.Effect, "replacedisappe", true); }
        public static void WuFuLinMe(GameState client) { client.Entity.Update(_String.Effect, "WuFuLinMe", true); }
        public static void replacedisapp(GameState client) { client.Entity.Update(_String.Effect, "replacedisapp", true); }
        public static void YiFanFengS(GameState client) { client.Entity.Update(_String.Effect, "YiFanFengS", true); }
        public static void endureXPword(GameState client) { client.Entity.Update(_String.Effect, "endureXPword", true); }
        public static void zf2_e067(GameState client) { client.Entity.Update(_String.Effect, "zf2-e067", true); }
        public static void zf2_e128(GameState client) { client.Entity.Update(_String.Effect, "zf2-e128", true); }
        public static void ScapegoatSwi(GameState client) { client.Entity.Update(_String.Effect, "ScapegoatSwi", true); }
        public static void zf2_e129(GameState client) { client.Entity.Update(_String.Effect, "zf2-e129", true); }
        public static void cyclonehanddart02(GameState client) { client.Entity.Update(_String.Effect, "cyclonehanddart02", true); }
        public static void poisonblast03(GameState client) { client.Entity.Update(_String.Effect, "poisonblast03", true); }
        public static void perfect2(GameState client) { client.Entity.Update(_String.Effect, "perfect", true); }
        public static void cyclonehanddart03(GameState client) { client.Entity.Update(_String.Effect, "cyclonehanddart03", true); }
        public static void poisonblast04(GameState client) { client.Entity.Update(_String.Effect, "poisonblast04", true); }
        public static void cyclonehanddart04(GameState client) { client.Entity.Update(_String.Effect, "cyclonehanddart04", true); }
        public static void poisonblast05(GameState client) { client.Entity.Update(_String.Effect, "poisonblast05", true); }
        public static void QiXingGaoat(GameState client) { client.Entity.Update(_String.Effect, "QiXingGaoat", true); }
        public static void cyclonehanddart05(GameState client) { client.Entity.Update(_String.Effect, "cyclonehanddart05", true); }
        public static void cyclonehandend(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandend", true); }
        public static void Rab_Est_app2(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app2", true); }
        public static void cyclonehandend02(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandend02", true); }
        public static void poisoncast03(GameState client) { client.Entity.Update(_String.Effect, "poisoncast03", true); }
        public static void cyclonehandend05(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandend05", true); }
        public static void poisoncast0(GameState client) { client.Entity.Update(_String.Effect, "poisoncast0", true); }
        public static void poisonfog04(GameState client) { client.Entity.Update(_String.Effect, "poisonfog04", true); }
        public static void endureXPattack(GameState client) { client.Entity.Update(_String.Effect, "endureXPattack", true); }
        public static void SiJiPingAnat(GameState client) { client.Entity.Update(_String.Effect, "SiJiPingAnat", true); }
        public static void endureXPdeath(GameState client) { client.Entity.Update(_String.Effect, "endureXPdeath", true); }
        public static void attach_discharge04(GameState client) { client.Entity.Update(_String.Effect, "attach_discharge04", true); }
        public static void attach_discharge05(GameState client) { client.Entity.Update(_String.Effect, "attach_discharge05", true); }
        public static void mag_pro_sta(GameState client) { client.Entity.Update(_String.Effect, "mag_pro_sta", true); }
        public static void attach_fly(GameState client) { client.Entity.Update(_String.Effect, "attach_fly", true); }
        public static void meteor(GameState client) { client.Entity.Update(_String.Effect, "meteor", true); }
        public static void attach_fly02(GameState client) { client.Entity.Update(_String.Effect, "attach_fly02", true); }
        public static void Meteorflash(GameState client) { client.Entity.Update(_String.Effect, "Meteorflash", true); }
        public static void attach_fly03(GameState client) { client.Entity.Update(_String.Effect, "attach_fly03", true); }
        public static void nag_bom_acc(GameState client) { client.Entity.Update(_String.Effect, "nag_bom_acc", true); }
        public static void attach_fly04(GameState client) { client.Entity.Update(_String.Effect, "attach_fly04", true); }
        public static void nag_bom_ass(GameState client) { client.Entity.Update(_String.Effect, "nag_bom_ass", true); }
        public static void attach_fly05(GameState client) { client.Entity.Update(_String.Effect, "attach_fly05", true); }
        public static void poisonattack(GameState client) { client.Entity.Update(_String.Effect, "poisonattack", true); }
        public static void Bladefrost(GameState client) { client.Entity.Update(_String.Effect, "Bladefrost", true); }
        public static void poisonattack02(GameState client) { client.Entity.Update(_String.Effect, "poisonattack02", true); }
        public static void blo_sic_lig(GameState client) { client.Entity.Update(_String.Effect, "blo_sic_lig", true); }
        public static void poisonattack03(GameState client) { client.Entity.Update(_String.Effect, "poisonattack03", true); }
        public static void break_accept(GameState client) { client.Entity.Update(_String.Effect, "break_accept", true); }
        public static void poisonattack04(GameState client) { client.Entity.Update(_String.Effect, "poisonattack04", true); }
        public static void break_accept02(GameState client) { client.Entity.Update(_String.Effect, "break_accept02", true); }
        public static void poisonattack05(GameState client) { client.Entity.Update(_String.Effect, "poisonattack05", true); }
        public static void acc_ass_bul(GameState client) { client.Entity.Update(_String.Effect, "acc_ass_bul", true); }
        public static void cyclonehanddart(GameState client) { client.Entity.Update(_String.Effect, "cyclonehanddart", true); }
        public static void poisonblast02(GameState client) { client.Entity.Update(_String.Effect, "poisonblast02", true); }
        public static void ScapegoatSwitchOpen03(GameState client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen03", true); }
        public static void acc_ass_muz(GameState client) { client.Entity.Update(_String.Effect, "acc_ass_muz", true); }
        public static void pro_tir_sta(GameState client) { client.Entity.Update(_String.Effect, "pro_tir_sta", true); }
        public static void acc_fir_acc(GameState client) { client.Entity.Update(_String.Effect, "acc_fir_acc", true); }
        public static void Rab_Est_acc(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_acc", true); }
        public static void Assassin(GameState client) { client.Entity.Update(_String.Effect, "Assassin", true); }
        public static void Rab_Est_app0(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app0", true); }
        public static void attach_accept(GameState client) { client.Entity.Update(_String.Effect, "attach_accept", true); }
        public static void attach_accept02(GameState client) { client.Entity.Update(_String.Effect, "attach_accept02", true); }
        public static void goose(GameState client) { client.Entity.Update(_String.Effect, "goose", true); }
        public static void swordcaromaccept(GameState client) { client.Entity.Update(_String.Effect, "swordcaromaccept", true); }
        public static void attach_accept03(GameState client) { client.Entity.Update(_String.Effect, "attach_accept03", true); }
        public static void Rab_Est_app3(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app3", true); }
        public static void attach_accept04(GameState client) { client.Entity.Update(_String.Effect, "attach_accept04", true); }
        public static void Rab_Est_app4(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app4", true); }
        public static void attach_accept05(GameState client) { client.Entity.Update(_String.Effect, "attach_accept05", true); }
        public static void attach_continuance02(GameState client) { client.Entity.Update(_String.Effect, "attach_continuance02", true); }
        public static void attach_continuance03(GameState client) { client.Entity.Update(_String.Effect, "attach_continuance03", true); }
        public static void attach_continuance04(GameState client) { client.Entity.Update(_String.Effect, "attach_continuance04", true); }
        public static void attach_continuance05(GameState client) { client.Entity.Update(_String.Effect, "attach_continuance05", true); }
        public static void Rab_Est_app9(GameState client) { client.Entity.Update(_String.Effect, "Rab_Est_app9", true); }
        public static void attach_discharge(GameState client) { client.Entity.Update(_String.Effect, "attach_discharge", true); }
        public static void KOTeleport(GameState client) { client.Entity.Update(_String.Effect, "KOTeleport", true); }
        public static void attach_discharge02(GameState client) { client.Entity.Update(_String.Effect, "attach_discharge02", true); }
        public static void let_gun_sho(GameState client) { client.Entity.Update(_String.Effect, "let_gun_sho", true); }
        public static void WarFlagEscortBegin(GameState client) { client.Entity.Update(_String.Effect, "WarFlagEscortBegin", true); }
        public static void attach_discharge03(GameState client) { client.Entity.Update(_String.Effect, "attach_discharge03", true); }
        public static void mag_pro_ari(GameState client) { client.Entity.Update(_String.Effect, "mag_pro_ari", true); }
        public static void cyclonehand04(GameState client) { client.Entity.Update(_String.Effect, "cyclonehand04", true); }
        public static void mag_pro_rep(GameState client) { client.Entity.Update(_String.Effect, "mag_pro_rep", true); }
        public static void cyclonehand05(GameState client) { client.Entity.Update(_String.Effect, "cyclonehand05", true); }
        public static void poisonparoxysm03(GameState client) { client.Entity.Update(_String.Effect, "poisonparoxysm03", true); }
        public static void cyclonehandattack(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandattack", true); }
        public static void poisonparoxysm04(GameState client) { client.Entity.Update(_String.Effect, "poisonparoxysm04", true); }
        public static void cyclonehandattack02(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandattack02", true); }
        public static void poisonparoxysm05(GameState client) { client.Entity.Update(_String.Effect, "poisonparoxysm05", true); }
        public static void cyclonehandattack2(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandattack2", true); }
        public static void poisonstate02(GameState client) { client.Entity.Update(_String.Effect, "poisonstate02", true); }
        public static void cyclonehandattack05(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandattack05", true); }
        public static void poisonstate03(GameState client) { client.Entity.Update(_String.Effect, "poisonstate03", true); }
        public static void cyclonehandcycle(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandcycle", true); }
        public static void poisonstate04(GameState client) { client.Entity.Update(_String.Effect, "poisonstate04", true); }
        public static void cyclonehandcycle02(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandcycle02", true); }
        public static void poisonstate05(GameState client) { client.Entity.Update(_String.Effect, "poisonstate05", true); }
        public static void cyclonehandcycle03(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandcycle03", true); }
        public static void pro_gre_assbom(GameState client) { client.Entity.Update(_String.Effect, "pro_gre_assbom", true); }
        public static void cyclonehandcycle04(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandcycle04", true); }
        public static void pro_gre_assflo(GameState client) { client.Entity.Update(_String.Effect, "pro_gre_assflo", true); }
        public static void cyclonehandcycle05(GameState client) { client.Entity.Update(_String.Effect, "cyclonehandcycle05", true); }
        public static void pro_tir_assbom(GameState client) { client.Entity.Update(_String.Effect, "pro_tir_assbom", true); }
        public static void break_accept03(GameState client) { client.Entity.Update(_String.Effect, "break_accept03", true); }
        public static void endureXPwordzai(GameState client) { client.Entity.Update(_String.Effect, "endureXPwordzai", true); }
        public static void pro_tir_assflo(GameState client) { client.Entity.Update(_String.Effect, "pro_tir_assflo", true); }
        public static void break_accept04(GameState client) { client.Entity.Update(_String.Effect, "break_accept04", true); }
        public static void endureXPwordzhe(GameState client) { client.Entity.Update(_String.Effect, "endureXPwordzhe", true); }
        public static void ScapegoatSwitchOpen04(GameState client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen04", true); }
        public static void break_accept05(GameState client) { client.Entity.Update(_String.Effect, "break_accept05", true); }
        public static void endureXPwordzhen(GameState client) { client.Entity.Update(_String.Effect, "endureXPwordzhen", true); }
        public static void ScapegoatSwitchOpen05(GameState client) { client.Entity.Update(_String.Effect, "ScapegoatSwitchOpen05", true); }
        public static void break_start(GameState client) { client.Entity.Update(_String.Effect, "break_start", true); }
        public static void EquipBroken(GameState client) { client.Entity.Update(_String.Effect, "EquipBroken", true); }
        public static void sea(GameState client) { client.Entity.Update(_String.Effect, "sea", true); }
        public static void break_start02(GameState client) { client.Entity.Update(_String.Effect, "break_start02", true); }
        public static void gainTeleport(GameState client) { client.Entity.Update(_String.Effect, "gainTeleport", true); }
        public static void break_start03(GameState client) { client.Entity.Update(_String.Effect, "break_start03", true); }
        public static void poisoncast02(GameState client) { client.Entity.Update(_String.Effect, "poisoncast02", true); }
        public static void break_start04(GameState client) { client.Entity.Update(_String.Effect, "break_start04", true); }
        public static void gro_wea_tor(GameState client) { client.Entity.Update(_String.Effect, "gro_wea_tor", true); }
        public static void swordcaromstart(GameState client) { client.Entity.Update(_String.Effect, "swordcaromstart", true); }
        public static void break_track(GameState client) { client.Entity.Update(_String.Effect, "break_track", true); }
        public static void Icearray(GameState client) { client.Entity.Update(_String.Effect, "Icearray", true); }
        public static void swordcaromstart02(GameState client) { client.Entity.Update(_String.Effect, "swordcaromstart02", true); }
        public static void break_track02(GameState client) { client.Entity.Update(_String.Effect, "break_track02", true); }
        public static void break_track03(GameState client) { client.Entity.Update(_String.Effect, "break_track03", true); }
        public static void break_track04(GameState client) { client.Entity.Update(_String.Effect, "break_track04", true); }
        public static void break_track05(GameState client) { client.Entity.Update(_String.Effect, "break_track05", true); }
        public static void bump2(GameState client) { client.Entity.Update(_String.Effect, "bump2", true); }
        public static void Knifespin(GameState client) { client.Entity.Update(_String.Effect, "Knifespin", true); }
        public static void tempest(GameState client) { client.Entity.Update(_String.Effect, "tempest", true); }
        public static void cyclonehand(GameState client) { client.Entity.Update(_String.Effect, "cyclonehand", true); }
        public static void poisonfog05(GameState client) { client.Entity.Update(_String.Effect, "poisonfog05", true); }
        public static void cyclonehand02(GameState client) { client.Entity.Update(_String.Effect, "cyclonehand02", true); }
        public static void poisonmiss(GameState client) { client.Entity.Update(_String.Effect, "poisonmiss", true); }
        public static void cyclonehand03(GameState client) { client.Entity.Update(_String.Effect, "cyclonehand03", true); }
        public static void poisonorigin(GameState client) { client.Entity.Update(_String.Effect, "poisonorigin", true); }
        public static void scene_goon(GameState client) { client.Entity.Update(_String.Effect, "scene_goon", true); }
        public static void flower3(GameState client) { client.Entity.Update(_String.Effect, "flower3", true); }
        public static void horse_aff(GameState client) { client.Entity.Update(_String.Effect, "horse_aff", true); }
        public static void horse_back(GameState client) { client.Entity.Update(_String.Effect, "horse_back", true); }
        public static void horse_run(GameState client) { client.Entity.Update(_String.Effect, "horse_run", true); }
        public static void ridmatch_colon(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_colon", true); }
        public static void ridmatch_eighth(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_eighth", true); }
        public static void ridmatch_fifth(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_fifth", true); }
        public static void ridmatch_first(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_first", true); }
        public static void ridmatch_fourth(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_fourth", true); }
        public static void ridmatch_ninth(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_ninth", true); }
        public static void bossimmunity(GameState client) { client.Entity.Update(_String.Effect, "bossimmunity", true); }
        public static void ridmatch_num0(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num0", true); }
        public static void ridmatch_num1(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num1", true); }
        public static void ridmatch_num2(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num2", true); }
        public static void ridmatch_num3(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num3", true); }
        public static void ridmatch_num4(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num4", true); }
        public static void ridmatch_num5(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num5", true); }
        public static void ridmatch_num6(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num6", true); }
        public static void ridmatch_num7(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num7", true); }
        public static void ridmatch_num8(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num8", true); }
        public static void ridmatch_num9(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_num9", true); }
        public static void ridmatch_second(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_second", true); }
        public static void ridmatch_seventh(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_seventh", true); }
        public static void ridmatch_sixth(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_sixth", true); }
        public static void ridmatch_tenth(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_tenth", true); }
        public static void ridmatch_third(GameState client) { client.Entity.Update(_String.Effect, "ridmatch_third", true); }
        public static void scene_app(GameState client) { client.Entity.Update(_String.Effect, "scene_app", true); }
        public static void scene_dis(GameState client) { client.Entity.Update(_String.Effect, "scene_dis", true); }
        public static void balloon1(GameState client) { client.Entity.Update(_String.Effect, "balloon1", true); }
        public static void balloon2(GameState client) { client.Entity.Update(_String.Effect, "balloon2", true); }
        public static void balloon3(GameState client) { client.Entity.Update(_String.Effect, "balloon3", true); }
        public static void balloon4(GameState client) { client.Entity.Update(_String.Effect, "balloon4", true); }
        public static void ff02(GameState client) { client.Entity.Update(_String.Effect, "ff02", true); }
        public static void ff03(GameState client) { client.Entity.Update(_String.Effect, "ff03", true); }
        public static void ff04(GameState client) { client.Entity.Update(_String.Effect, "ff04", true); }
        public static void ff05(GameState client) { client.Entity.Update(_String.Effect, "ff05", true); }
        public static void ff07(GameState client) { client.Entity.Update(_String.Effect, "ff07", true); }
        public static void ff08(GameState client) { client.Entity.Update(_String.Effect, "ff08", true); }
        public static void ff09(GameState client) { client.Entity.Update(_String.Effect, "ff09", true); }
        public static void ff12(GameState client) { client.Entity.Update(_String.Effect, "ff12", true); }
        public static void ff13(GameState client) { client.Entity.Update(_String.Effect, "ff13", true); }
        public static void ff14(GameState client) { client.Entity.Update(_String.Effect, "ff14", true); }
        public static void ff15(GameState client) { client.Entity.Update(_String.Effect, "ff15", true); }
        public static void ff16(GameState client) { client.Entity.Update(_String.Effect, "ff16", true); }
        public static void ff17(GameState client) { client.Entity.Update(_String.Effect, "ff17", true); }
        public static void ff18(GameState client) { client.Entity.Update(_String.Effect, "ff18", true); }
        public static void ff18a(GameState client) { client.Entity.Update(_String.Effect, "ff18a", true); }
        public static void ff18b(GameState client) { client.Entity.Update(_String.Effect, "ff18b", true); }
        public static void ff19(GameState client) { client.Entity.Update(_String.Effect, "ff19", true); }
        public static void ff20(GameState client) { client.Entity.Update(_String.Effect, "ff20", true); }
        public static void ff21(GameState client) { client.Entity.Update(_String.Effect, "ff21", true); }
        public static void ff22(GameState client) { client.Entity.Update(_String.Effect, "ff22", true); }
        public static void ff23(GameState client) { client.Entity.Update(_String.Effect, "ff23", true); }
        public static void flower1(GameState client) { client.Entity.Update(_String.Effect, "flower1", true); }
        public static void flower2(GameState client) { client.Entity.Update(_String.Effect, "flower2", true); }
        public static void interface215(GameState client) { client.Entity.Update(_String.Effect, "interface215", true); }
        public static void interface216(GameState client) { client.Entity.Update(_String.Effect, "interface216", true); }
        public static void keepon(GameState client) { client.Entity.Update(_String.Effect, "keepon", true); }
        public static void KOfire01(GameState client) { client.Entity.Update(_String.Effect, "KOfire01", true); }
        public static void listlock(GameState client) { client.Entity.Update(_String.Effect, "listlock", true); }
        public static void PKpack(GameState client) { client.Entity.Update(_String.Effect, "PKpack", true); }
        public static void PKpack_s(GameState client) { client.Entity.Update(_String.Effect, "PKpack_s", true); }
        public static void pkpunish(GameState client) { client.Entity.Update(_String.Effect, "pkpunish", true); }
        public static void roleword(GameState client) { client.Entity.Update(_String.Effect, "roleword", true); }
        public static void XP(GameState client) { client.Entity.Update(_String.Effect, "XP", true); }
        public static void fusebijou04(GameState client) { client.Entity.Update(_String.Effect, "fusebijou04", true); }
        public static void fusebijou05(GameState client) { client.Entity.Update(_String.Effect, "fusebijou05", true); }
        public static void fusebijou06(GameState client) { client.Entity.Update(_String.Effect, "fusebijou06", true); }
        public static void fusebijou07(GameState client) { client.Entity.Update(_String.Effect, "fusebijou07", true); }
        public static void fusesucceed(GameState client) { client.Entity.Update(_String.Effect, "fusesucceed", true); }
        public static void GemComposeFull(GameState client) { client.Entity.Update(_String.Effect, "GemComposeFull", true); }
        public static void GemComposeSuc700001(GameState client) { client.Entity.Update(_String.Effect, "GemComposeSuc700001", true); }
        public static void interface195(GameState client) { client.Entity.Update(_String.Effect, "interface195", true); }
        public static void interface196(GameState client) { client.Entity.Update(_String.Effect, "interface196", true); }
        public static void interface197(GameState client) { client.Entity.Update(_String.Effect, "interface197", true); }
        public static void interface198(GameState client) { client.Entity.Update(_String.Effect, "interface198", true); }
        public static void interface199(GameState client) { client.Entity.Update(_String.Effect, "interface199", true); }
        public static void interface200(GameState client) { client.Entity.Update(_String.Effect, "interface200", true); }
        public static void interface201(GameState client) { client.Entity.Update(_String.Effect, "interface201", true); }
        public static void interface202(GameState client) { client.Entity.Update(_String.Effect, "interface202", true); }
        public static void interface203(GameState client) { client.Entity.Update(_String.Effect, "interface203", true); }
        public static void interface204(GameState client) { client.Entity.Update(_String.Effect, "interface204", true); }
        public static void interface205(GameState client) { client.Entity.Update(_String.Effect, "interface205", true); }
        public static void interface206(GameState client) { client.Entity.Update(_String.Effect, "interface206", true); }
        public static void interface207(GameState client) { client.Entity.Update(_String.Effect, "interface207", true); }
        public static void interface208(GameState client) { client.Entity.Update(_String.Effect, "interface208", true); }
        public static void interface209(GameState client) { client.Entity.Update(_String.Effect, "interface209", true); }
        public static void interface210(GameState client) { client.Entity.Update(_String.Effect, "interface210", true); }
        public static void interface211(GameState client) { client.Entity.Update(_String.Effect, "interface211", true); }
        public static void interface212(GameState client) { client.Entity.Update(_String.Effect, "interface212", true); }
        public static void interface213(GameState client) { client.Entity.Update(_String.Effect, "interface213", true); }
        public static void interface214(GameState client) { client.Entity.Update(_String.Effect, "interface214", true); }
        public static void alternation(GameState client) { client.Entity.Update(_String.Effect, "alternation", true); }
        public static void award_res(GameState client) { client.Entity.Update(_String.Effect, "award_res", true); }
        public static void box_preview(GameState client) { client.Entity.Update(_String.Effect, "box_preview", true); }
        public static void box_weapon(GameState client) { client.Entity.Update(_String.Effect, "box_weapon", true); }
        public static void card_AllIn_cyc(GameState client) { client.Entity.Update(_String.Effect, "card_AllIn_cyc", true); }
        public static void card_Frankohead(GameState client) { client.Entity.Update(_String.Effect, "card_Frankohead", true); }
        public static void card_banner(GameState client) { client.Entity.Update(_String.Effect, "card_banner", true); }
        public static void card_beacon(GameState client) { client.Entity.Update(_String.Effect, "card_beacon", true); }
        public static void card_call_cyc(GameState client) { client.Entity.Update(_String.Effect, "card_call_cyc", true); }
        public static void card_Check(GameState client) { client.Entity.Update(_String.Effect, "card_Check", true); }
        public static void card_Fold_cyc(GameState client) { client.Entity.Update(_String.Effect, "card_Fold_cyc", true); }
        public static void card_lose(GameState client) { client.Entity.Update(_String.Effect, "card_lose", true); }
        public static void card_loseall(GameState client) { client.Entity.Update(_String.Effect, "card_loseall", true); }
        public static void card_Raise_cyc(GameState client) { client.Entity.Update(_String.Effect, "card_Raise_cyc", true); }
        public static void card_win(GameState client) { client.Entity.Update(_String.Effect, "card_win", true); }
        public static void chatclosebtn(GameState client) { client.Entity.Update(_String.Effect, "chatclosebtn", true); }
        public static void compose(GameState client) { client.Entity.Update(_String.Effect, "compose", true); }
        public static void dsoulaffuse(GameState client) { client.Entity.Update(_String.Effect, "dsoulaffuse", true); }
        public static void eqpdownlevitf(GameState client) { client.Entity.Update(_String.Effect, "eqpdownlevitf", true); }
        public static void equip_function(GameState client) { client.Entity.Update(_String.Effect, "equip_function", true); }
        public static void equip_openhole(GameState client) { client.Entity.Update(_String.Effect, "equip_openhole", true); }
        public static void EquipAppend(GameState client) { client.Entity.Update(_String.Effect, "EquipAppend", true); }
        public static void equiprebuild(GameState client) { client.Entity.Update(_String.Effect, "equiprebuild", true); }
        public static void expression(GameState client) { client.Entity.Update(_String.Effect, "expression", true); }
        public static void fusebijou01(GameState client) { client.Entity.Update(_String.Effect, "fusebijou01", true); }
        public static void fusebijou02(GameState client) { client.Entity.Update(_String.Effect, "fusebijou02", true); }
        public static void fusebijou03(GameState client) { client.Entity.Update(_String.Effect, "fusebijou03", true); }
        public static void firecracker_(GameState client) { client.Entity.Update(_String.Effect, "firecracker-", true); }
        public static void flash(GameState client) { client.Entity.Update(_String.Effect, "flash", true); }
        public static void foot01(GameState client) { client.Entity.Update(_String.Effect, "foot01", true); }
        public static void foot_xin(GameState client) { client.Entity.Update(_String.Effect, "foot-xin", true); }
        public static void good(GameState client) { client.Entity.Update(_String.Effect, "good", true); }
        public static void PKItemRewardEffect(GameState client) { client.Entity.Update(_String.Effect, "PKItemRewardEffect", true); }
        public static void hunpo02(GameState client) { client.Entity.Update(_String.Effect, "hunpo02", true); }
        public static void JiuJiuTongX2(GameState client) { client.Entity.Update(_String.Effect, "JiuJiuTongX", true); }
        public static void KylinCave(GameState client) { client.Entity.Update(_String.Effect, "KylinCave", true); }
        public static void placardbtnclew(GameState client) { client.Entity.Update(_String.Effect, "placardbtnclew", true); }
        public static void lightsword(GameState client) { client.Entity.Update(_String.Effect, "lightsword", true); }
        public static void LiuLiuDaSh(GameState client) { client.Entity.Update(_String.Effect, "LiuLiuDaSh", true); }
        public static void LoveCanyo(GameState client) { client.Entity.Update(_String.Effect, "LoveCanyo", true); }
        public static void LuckAbsorb(GameState client) { client.Entity.Update(_String.Effect, "LuckAbsorb", true); }
        public static void LuckDiffuse(GameState client) { client.Entity.Update(_String.Effect, "LuckDiffuse", true); }
        public static void Lucky(GameState client) { client.Entity.Update(_String.Effect, "Lucky", true); }
        public static void LuckyGuy(GameState client) { client.Entity.Update(_String.Effect, "LuckyGuy", true); }
        public static void magic(GameState client) { client.Entity.Update(_String.Effect, "magic", true); }
        public static void mammon(GameState client) { client.Entity.Update(_String.Effect, "mammon", true); }
        public static void wumo_godap(GameState client) { client.Entity.Update(_String.Effect, "wumo_godap", true); }
        public static void wumo_godcyc(GameState client) { client.Entity.Update(_String.Effect, "wumo_godcyc", true); }
        public static void wumo_jw(GameState client) { client.Entity.Update(_String.Effect, "wumo_jw", true); }
        public static void wumo_onap(GameState client) { client.Entity.Update(_String.Effect, "wumo_onap", true); }
        public static void wumo_oncyc(GameState client) { client.Entity.Update(_String.Effect, "wumo_oncyc", true); }
        public static void wumo_ondis(GameState client) { client.Entity.Update(_String.Effect, "wumo_ondis", true); }
        public static void wumo_pdac(GameState client) { client.Entity.Update(_String.Effect, "wumo_pdac", true); }
        public static void wumo_whi(GameState client) { client.Entity.Update(_String.Effect, "wumo_whi", true); }
        public static void xdn_fi1(GameState client) { client.Entity.Update(_String.Effect, "xdn_fi1", true); }
        public static void xdn_fi2(GameState client) { client.Entity.Update(_String.Effect, "xdn_fi2", true); }
        public static void xidag_bafi(GameState client) { client.Entity.Update(_String.Effect, "xidag_bafi", true); }
        public static void xidag_d901(GameState client) { client.Entity.Update(_String.Effect, "xidag_d901", true); }
        public static void xidag_d902(GameState client) { client.Entity.Update(_String.Effect, "xidag_d902", true); }
        public static void xidag_da(GameState client) { client.Entity.Update(_String.Effect, "xidag_da", true); }
        public static void xidag_f901(GameState client) { client.Entity.Update(_String.Effect, "xidag_f901", true); }
        public static void xidag_f902(GameState client) { client.Entity.Update(_String.Effect, "xidag_f902", true); }
        public static void xidag_f903(GameState client) { client.Entity.Update(_String.Effect, "xidag_f903", true); }
        public static void xidag_fcy(GameState client) { client.Entity.Update(_String.Effect, "xidag_fcy", true); }
        public static void xnd_bat_fly(GameState client) { client.Entity.Update(_String.Effect, "xnd_bat_fly", true); }
        public static void zfregime1(GameState client) { client.Entity.Update(_String.Effect, "zfregime1", true); }
        public static void zfregime2(GameState client) { client.Entity.Update(_String.Effect, "zfregime2", true); }
        public static void zfregime3(GameState client) { client.Entity.Update(_String.Effect, "zfregime3", true); }
        public static void zfregime4(GameState client) { client.Entity.Update(_String.Effect, "zfregime4", true); }
        public static void zhtx_attack(GameState client) { client.Entity.Update(_String.Effect, "zhtx_attack", true); }
        public static void zs_dpgd_dong(GameState client) { client.Entity.Update(_String.Effect, "zs_dpgd_dong", true); }
        public static void ws_hytxj_att(GameState client) { client.Entity.Update(_String.Effect, "ws_hytxj_att", true); }
        public static void ws_hytxj_b_n(GameState client) { client.Entity.Update(_String.Effect, "ws_hytxj_b_n", true); }
        public static void ws_hytxj_hit(GameState client) { client.Entity.Update(_String.Effect, "ws_hytxj_hit", true); }
        public static void ws_hytxj_r_n(GameState client) { client.Entity.Update(_String.Effect, "ws_hytxj_r_n", true); }
        public static void ws_hytxj_y_n(GameState client) { client.Entity.Update(_String.Effect, "ws_hytxj_y_n", true); }
        public static void wsarm_electhig(GameState client) { client.Entity.Update(_String.Effect, "wsarm_electhig", true); }
        public static void wsarm_electlow(GameState client) { client.Entity.Update(_String.Effect, "wsarm_electlow", true); }
        public static void wsarm_firehig(GameState client) { client.Entity.Update(_String.Effect, "wsarm_firehig", true); }
        public static void wsarm_firelow(GameState client) { client.Entity.Update(_String.Effect, "wsarm_firelow", true); }
        public static void wsarm_goldhig(GameState client) { client.Entity.Update(_String.Effect, "wsarm_goldhig", true); }
        public static void wsarm_goldlow(GameState client) { client.Entity.Update(_String.Effect, "wsarm_goldlow", true); }
        public static void wsarm_waterhig(GameState client) { client.Entity.Update(_String.Effect, "wsarm_waterhig", true); }
        public static void wsarm_woodhig(GameState client) { client.Entity.Update(_String.Effect, "wsarm_woodhig", true); }
        public static void wsarm_woodlow(GameState client) { client.Entity.Update(_String.Effect, "wsarm_woodlow", true); }
        public static void wsmhcxq_att(GameState client) { client.Entity.Update(_String.Effect, "wsmhcxq_att", true); }
        public static void wsmhcxq_hit(GameState client) { client.Entity.Update(_String.Effect, "wsmhcxq_hit", true); }
        public static void wspk_eighth(GameState client) { client.Entity.Update(_String.Effect, "wspk_eighth", true); }
        public static void wspk_first(GameState client) { client.Entity.Update(_String.Effect, "wspk_first", true); }
        public static void wspk_second(GameState client) { client.Entity.Update(_String.Effect, "wspk_second", true); }
        public static void wspk_third(GameState client) { client.Entity.Update(_String.Effect, "wspk_third", true); }
        public static void wssfs_app(GameState client) { client.Entity.Update(_String.Effect, "wssfs_app", true); }
        public static void wssfs_cyc(GameState client) { client.Entity.Update(_String.Effect, "wssfs_cyc", true); }
        public static void wssfs_dis(GameState client) { client.Entity.Update(_String.Effect, "wssfs_dis", true); }
        public static void wssfs_fire(GameState client) { client.Entity.Update(_String.Effect, "wssfs_fire", true); }
        public static void wumo_dxacc(GameState client) { client.Entity.Update(_String.Effect, "wumo_dxacc", true); }
        public static void wumo_dxap(GameState client) { client.Entity.Update(_String.Effect, "wumo_dxap", true); }
        public static void attack035(GameState client) { client.Entity.Update(_String.Effect, "attack035", true); }
        public static void gddge(GameState client) { client.Entity.Update(_String.Effect, "410239", true); }
        public static void geete(GameState client) { client.Entity.Update(_String.Effect, "410289", true); }
        public static void ettete(GameState client) { client.Entity.Update(_String.Effect, "410339", true); }
        public static void magic_400029_beat(GameState client) { client.Entity.Update(_String.Effect, "magic_400029_beat", true); }
        public static void monsterbeattack_fire(GameState client) { client.Entity.Update(_String.Effect, "monsterbeattack_fire", true); }
        public static void Status_Stop_cyc(GameState client) { client.Entity.Update(_String.Effect, "Status_Stop_cyc", true); }
        public static void eud_431_2(GameState client) { client.Entity.Update(_String.Effect, "eud_431_2", true); }
        public static void noconfirm096(GameState client) { client.Entity.Update(_String.Effect, "noconfirm096", true); }
        public static void wyattack(GameState client) { client.Entity.Update(_String.Effect, "wyattack", true); }
        public static void clewarbignor(GameState client) { client.Entity.Update(_String.Effect, "clewarbignor", true); }
        public static void clewarbigred(GameState client) { client.Entity.Update(_String.Effect, "clewarbigred", true); }
        public static void clewarsmall(GameState client) { client.Entity.Update(_String.Effect, "clewarsmall", true); }
        public static void ninjapk_third(GameState client) { client.Entity.Update(_String.Effect, "ninjapk_third", true); }
        public static void tread_ref(GameState client) { client.Entity.Update(_String.Effect, "tread_ref", true); }
        public static void ninjia_superc(GameState client) { client.Entity.Update(_String.Effect, "ninjia_superc", true); }
        public static void trojanpk_eight(GameState client) { client.Entity.Update(_String.Effect, "trojanpk_eight", true); }
        public static void ninjia_superc1(GameState client) { client.Entity.Update(_String.Effect, "ninjia_superc1", true); }
        public static void trojanpk_second(GameState client) { client.Entity.Update(_String.Effect, "trojanpk_second", true); }
        public static void ord_fir(GameState client) { client.Entity.Update(_String.Effect, "ord_fir", true); }
        public static void trojanpk_third(GameState client) { client.Entity.Update(_String.Effect, "trojanpk_third", true); }
        public static void ord_sec(GameState client) { client.Entity.Update(_String.Effect, "ord_sec", true); }
        public static void tulip_flower_charm1(GameState client) { client.Entity.Update(_String.Effect, "tulip-flower-charm1", true); }
        public static void ord_thi(GameState client) { client.Entity.Update(_String.Effect, "ord_thi", true); }
        public static void tulip_flower_charm2(GameState client) { client.Entity.Update(_String.Effect, "tulip-flower-charm2", true); }
        public static void partbehit(GameState client) { client.Entity.Update(_String.Effect, "partbehit", true); }
        public static void tulip_flower_charm3(GameState client) { client.Entity.Update(_String.Effect, "tulip-flower-charm3", true); }
        public static void partbehithead(GameState client) { client.Entity.Update(_String.Effect, "partbehithead", true); }
        public static void tulip_flower_full(GameState client) { client.Entity.Update(_String.Effect, "tulip-flower-full", true); }
        public static void pigeon(GameState client) { client.Entity.Update(_String.Effect, "pigeon", true); }
        public static void tulip_flower_g_1(GameState client) { client.Entity.Update(_String.Effect, "tulip-flower-g-1", true); }
        public static void pir_non_dre(GameState client) { client.Entity.Update(_String.Effect, "pir_non_dre", true); }
        public static void tulip_flower_rain(GameState client) { client.Entity.Update(_String.Effect, "tulip-flower-rain", true); }
        public static void piratenonsuch(GameState client) { client.Entity.Update(_String.Effect, "piratenonsuch", true); }
        public static void WarFlagEscortSuc(GameState client) { client.Entity.Update(_String.Effect, "WarFlagEscortSuc", true); }
        public static void moveadding(GameState client) { client.Entity.Update(_String.Effect, "moveadding", true); }
        public static void stipple_bdh(GameState client) { client.Entity.Update(_String.Effect, "stipple_bdh", true); }
        public static void moveallay(GameState client) { client.Entity.Update(_String.Effect, "moveallay", true); }
        public static void stipple_dhz(GameState client) { client.Entity.Update(_String.Effect, "stipple_dhz", true); }
        public static void moveallaying(GameState client) { client.Entity.Update(_String.Effect, "moveallaying", true); }
        public static void stipple_jx(GameState client) { client.Entity.Update(_String.Effect, "stipple_jx", true); }
        public static void new_goods_tips(GameState client) { client.Entity.Update(_String.Effect, "new_goods_tips", true); }
        public static void stipple_kdh(GameState client) { client.Entity.Update(_String.Effect, "stipple_kdh", true); }
        public static void NEW_flower_charm1(GameState client) { client.Entity.Update(_String.Effect, "NEW-flower-charm1", true); }
        public static void suc_sys_fun(GameState client) { client.Entity.Update(_String.Effect, "suc_sys_fun", true); }
        public static void NEW_flower_charm2(GameState client) { client.Entity.Update(_String.Effect, "NEW-flower-charm2", true); }
        public static void switchitem(GameState client) { client.Entity.Update(_String.Effect, "switchitem", true); }
        public static void NEW_flower_charm3(GameState client) { client.Entity.Update(_String.Effect, "NEW-flower-charm3", true); }
        public static void TakeOnLilySuit(GameState client) { client.Entity.Update(_String.Effect, "TakeOnLilySuit", true); }
        public static void NEW_flower_full(GameState client) { client.Entity.Update(_String.Effect, "NEW-flower-full", true); }
        public static void TakeOnOrchisSuit(GameState client) { client.Entity.Update(_String.Effect, "TakeOnOrchisSuit", true); }
        public static void NEW_flower_g_1(GameState client) { client.Entity.Update(_String.Effect, "NEW-flower-g-1", true); }
        public static void TakeOnRoseSuit(GameState client) { client.Entity.Update(_String.Effect, "TakeOnRoseSuit", true); }
        public static void NEW_flower_r_1(GameState client) { client.Entity.Update(_String.Effect, "NEW-flower-r-1", true); }
        public static void TakeOnTulipSuit(GameState client) { client.Entity.Update(_String.Effect, "TakeOnTulipSuit", true); }
        public static void NEW_flower_rain(GameState client) { client.Entity.Update(_String.Effect, "NEW-flower-rain", true); }
        public static void targetshit(GameState client) { client.Entity.Update(_String.Effect, "targetshit", true); }
        public static void newmonbro(GameState client) { client.Entity.Update(_String.Effect, "newmonbro", true); }
        public static void taskcomplete(GameState client) { client.Entity.Update(_String.Effect, "taskcomplete", true); }
        public static void Ninja120(GameState client) { client.Entity.Update(_String.Effect, "Ninja120", true); }
        public static void TaskFail(GameState client) { client.Entity.Update(_String.Effect, "TaskFail", true); }
        public static void ninjapk_eight(GameState client) { client.Entity.Update(_String.Effect, "ninjapk_eight", true); }
        public static void taskhalf(GameState client) { client.Entity.Update(_String.Effect, "taskhalf", true); }
        public static void ninjapk_second(GameState client) { client.Entity.Update(_String.Effect, "ninjapk_second", true); }
        public static void tread_acc(GameState client) { client.Entity.Update(_String.Effect, "tread_acc", true); }
        public static void mortuary_bedbug1(GameState client) { client.Entity.Update(_String.Effect, "mortuary_bedbug1", true); }
        public static void spoondrift01(GameState client) { client.Entity.Update(_String.Effect, "spoondrift01", true); }
        public static void mortuary_bedbug2(GameState client) { client.Entity.Update(_String.Effect, "mortuary_bedbug2", true); }
        public static void sports_failure(GameState client) { client.Entity.Update(_String.Effect, "sports_failure", true); }
        public static void mortuary_cobweb1(GameState client) { client.Entity.Update(_String.Effect, "mortuary_cobweb1", true); }
        public static void sports_victory(GameState client) { client.Entity.Update(_String.Effect, "sports_victory", true); }
        public static void mortuary_cobweb2(GameState client) { client.Entity.Update(_String.Effect, "mortuary_cobweb2", true); }
        public static void sprayatt914(GameState client) { client.Entity.Update(_String.Effect, "sprayatt914", true); }
        public static void mortuary_roach1(GameState client) { client.Entity.Update(_String.Effect, "mortuary_roach1", true); }
        public static void sscg_cjj_hitg(GameState client) { client.Entity.Update(_String.Effect, "sscg_cjj_hitg", true); }
        public static void mortuary_roach2(GameState client) { client.Entity.Update(_String.Effect, "mortuary_roach2", true); }
        public static void ssch_wlhd_fir(GameState client) { client.Entity.Update(_String.Effect, "ssch_wlhd_fir", true); }
        public static void mortuary_soul1(GameState client) { client.Entity.Update(_String.Effect, "mortuary_soul1", true); }
        public static void ssch_wlhd_hit(GameState client) { client.Entity.Update(_String.Effect, "ssch_wlhd_hit", true); }
        public static void mortuary_soul2(GameState client) { client.Entity.Update(_String.Effect, "mortuary_soul2", true); }
        public static void sscs_htsd_app(GameState client) { client.Entity.Update(_String.Effect, "sscs_htsd_app", true); }
        public static void move_continue(GameState client) { client.Entity.Update(_String.Effect, "move_continue", true); }
        public static void sscs_htsd_cyc(GameState client) { client.Entity.Update(_String.Effect, "sscs_htsd_cyc", true); }
        public static void move_improve(GameState client) { client.Entity.Update(_String.Effect, "move_improve", true); }
        public static void sscs_htsd_dis(GameState client) { client.Entity.Update(_String.Effect, "sscs_htsd_dis", true); }
        public static void moveadd(GameState client) { client.Entity.Update(_String.Effect, "moveadd", true); }
        public static void statusweak(GameState client) { client.Entity.Update(_String.Effect, "statusweak", true); }
        public static void longpi5_452(GameState client) { client.Entity.Update(_String.Effect, "longpi5_452", true); }
        public static void sea_ver_fir(GameState client) { client.Entity.Update(_String.Effect, "sea_ver_fir", true); }
        public static void longpi6_452(GameState client) { client.Entity.Update(_String.Effect, "longpi6_452", true); }
        public static void sea_ver_sec(GameState client) { client.Entity.Update(_String.Effect, "sea_ver_sec", true); }
        public static void longpi7_452(GameState client) { client.Entity.Update(_String.Effect, "longpi7_452", true); }
        public static void sea_ver_thi(GameState client) { client.Entity.Update(_String.Effect, "sea_ver_thi", true); }
        public static void longpi8_452(GameState client) { client.Entity.Update(_String.Effect, "longpi8_452", true); }
        public static void seismatt_01(GameState client) { client.Entity.Update(_String.Effect, "seismatt_01", true); }
        public static void seismatt_02(GameState client) { client.Entity.Update(_String.Effect, "seismatt_02", true); }
        public static void mate_pk_01(GameState client) { client.Entity.Update(_String.Effect, "mate_pk_01", true); }
        public static void seismatt_03(GameState client) { client.Entity.Update(_String.Effect, "seismatt_03", true); }
        public static void mate_pk_02(GameState client) { client.Entity.Update(_String.Effect, "mate_pk_02", true); }
        public static void sen_gif_col(GameState client) { client.Entity.Update(_String.Effect, "sen_gif_col", true); }
        public static void mate_pk_03(GameState client) { client.Entity.Update(_String.Effect, "mate_pk_03", true); }
        public static void sen_gif_ful(GameState client) { client.Entity.Update(_String.Effect, "sen_gif_ful", true); }
        public static void mate_pk_08(GameState client) { client.Entity.Update(_String.Effect, "mate_pk_08", true); }
        public static void sen_gif_sen(GameState client) { client.Entity.Update(_String.Effect, "sen_gif_sen", true); }
        public static void minmapflag(GameState client) { client.Entity.Update(_String.Effect, "minmapflag", true); }
        public static void sex_pk_gir(GameState client) { client.Entity.Update(_String.Effect, "sex_pk_gir", true); }
        public static void end_task(GameState client) { client.Entity.Update(_String.Effect, "end_task", true); }
        public static void monkalnonsuch(GameState client) { client.Entity.Update(_String.Effect, "monkalnonsuch", true); }
        public static void sex_pk_man(GameState client) { client.Entity.Update(_String.Effect, "sex_pk_man", true); }
        public static void monkalnonsuch1(GameState client) { client.Entity.Update(_String.Effect, "monkalnonsuch1", true); }
        public static void ShieldBlock(GameState client) { client.Entity.Update(_String.Effect, "ShieldBlock", true); }
        public static void moonpk_eight(GameState client) { client.Entity.Update(_String.Effect, "moonpk_eight", true); }
        public static void slowliquid(GameState client) { client.Entity.Update(_String.Effect, "slowliquid", true); }
        public static void moonpk_second(GameState client) { client.Entity.Update(_String.Effect, "moonpk_second", true); }
        public static void s_motive_surf02(GameState client) { client.Entity.Update(_String.Effect, "s-motive-surf02", true); }
        public static void moonpk_third(GameState client) { client.Entity.Update(_String.Effect, "moonpk_third", true); }
        public static void s_motive_surf03(GameState client) { client.Entity.Update(_String.Effect, "s-motive-surf03", true); }
        public static void jypk130up_js(GameState client) { client.Entity.Update(_String.Effect, "jypk130up_js", true); }
        public static void riga_flacc(GameState client) { client.Entity.Update(_String.Effect, "riga_flacc", true); }
        public static void jypk130up_th(GameState client) { client.Entity.Update(_String.Effect, "jypk130up_th", true); }
        public static void riga_flap(GameState client) { client.Entity.Update(_String.Effect, "riga_flap", true); }
        public static void jypk130up_zy(GameState client) { client.Entity.Update(_String.Effect, "jypk130up_zy", true); }
        public static void rockdownatt(GameState client) { client.Entity.Update(_String.Effect, "rockdownatt", true); }
        public static void lighbo(GameState client) { client.Entity.Update(_String.Effect, "lighbo", true); }
        public static void roundrobingw(GameState client) { client.Entity.Update(_String.Effect, "roundrobingw", true); }
        public static void lighls(GameState client) { client.Entity.Update(_String.Effect, "lighls", true); }
        public static void runoffingw(GameState client) { client.Entity.Update(_String.Effect, "runoffingw", true); }
        public static void longci4_453(GameState client) { client.Entity.Update(_String.Effect, "longci4_453", true); }
        public static void scene_bedbladder(GameState client) { client.Entity.Update(_String.Effect, "scene_bedbladder", true); }
        public static void longci5_453(GameState client) { client.Entity.Update(_String.Effect, "longci5_453", true); }
        public static void scene_largefish(GameState client) { client.Entity.Update(_String.Effect, "scene_largefish", true); }
        public static void longci6_453(GameState client) { client.Entity.Update(_String.Effect, "longci6_453", true); }
        public static void scene_transmissions(GameState client) { client.Entity.Update(_String.Effect, "scene_transmissions", true); }
        public static void longci7_453(GameState client) { client.Entity.Update(_String.Effect, "longci7_453", true); }
        public static void scholar(GameState client) { client.Entity.Update(_String.Effect, "scholar", true); }
        public static void longci8_453(GameState client) { client.Entity.Update(_String.Effect, "longci8_453", true); }
        public static void sea_mis_eff(GameState client) { client.Entity.Update(_String.Effect, "sea_mis_eff", true); }
        public static void longpi4_452(GameState client) { client.Entity.Update(_String.Effect, "longpi4_452", true); }
        public static void sea_ver_eig(GameState client) { client.Entity.Update(_String.Effect, "sea_ver_eig", true); }
        public static void jsb_rayg_fir(GameState client) { client.Entity.Update(_String.Effect, "jsb_rayg_fir", true); }
        public static void property_wood(GameState client) { client.Entity.Update(_String.Effect, "property_wood", true); }
        public static void jsb_rayg_hit(GameState client) { client.Entity.Update(_String.Effect, "jsb_rayg_hit", true); }
        public static void ptjeff_pul(GameState client) { client.Entity.Update(_String.Effect, "ptjeff_pul", true); }
        public static void jsb_reva_att(GameState client) { client.Entity.Update(_String.Effect, "jsb_reva_att", true); }
        public static void rank(GameState client) { client.Entity.Update(_String.Effect, "rank", true); }
        public static void jsb_reva_fir(GameState client) { client.Entity.Update(_String.Effect, "jsb_reva_fir", true); }
        public static void rdeltoid_app(GameState client) { client.Entity.Update(_String.Effect, "rdeltoid_app", true); }
        public static void jsb_reva_hit(GameState client) { client.Entity.Update(_String.Effect, "jsb_reva_hit", true); }
        public static void rdeltoid_cyc(GameState client) { client.Entity.Update(_String.Effect, "rdeltoid_cyc", true); }
        public static void jsb_reva_pre(GameState client) { client.Entity.Update(_String.Effect, "jsb_reva_pre", true); }
        public static void rdeltoid_dis(GameState client) { client.Entity.Update(_String.Effect, "rdeltoid_dis", true); }
        public static void jsb_reva_sin(GameState client) { client.Entity.Update(_String.Effect, "jsb_reva_sin", true); }
        public static void replymove(GameState client) { client.Entity.Update(_String.Effect, "replymove", true); }
        public static void jsb_skyg_att(GameState client) { client.Entity.Update(_String.Effect, "jsb_skyg_att", true); }
        public static void RichGod_Money(GameState client) { client.Entity.Update(_String.Effect, "RichGod_Money", true); }
        public static void jsb_skyg_pre(GameState client) { client.Entity.Update(_String.Effect, "jsb_skyg_pre", true); }
        public static void ride_down(GameState client) { client.Entity.Update(_String.Effect, "ride_down", true); }
        public static void juren(GameState client) { client.Entity.Update(_String.Effect, "juren", true); }
        public static void ride_faint(GameState client) { client.Entity.Update(_String.Effect, "ride_faint", true); }
        public static void jypk130down_gs(GameState client) { client.Entity.Update(_String.Effect, "jypk130down_gs", true); }
        public static void ride_odd(GameState client) { client.Entity.Update(_String.Effect, "ride_odd", true); }
        public static void jypk130down_hy(GameState client) { client.Entity.Update(_String.Effect, "jypk130down_hy", true); }
        public static void ride_screen(GameState client) { client.Entity.Update(_String.Effect, "ride_screen", true); }
        public static void jypk130down_jr(GameState client) { client.Entity.Update(_String.Effect, "jypk130down_jr", true); }
        public static void ride_suck(GameState client) { client.Entity.Update(_String.Effect, "ride_suck", true); }
        public static void m1(GameState client) { client.Entity.Update(_String.Effect, "m1", true); }
        public static void jypk130down_xc(GameState client) { client.Entity.Update(_String.Effect, "jypk130down_xc", true); }
        public static void ride_up(GameState client) { client.Entity.Update(_String.Effect, "ride_up", true); }
        public static void m2(GameState client) { client.Entity.Update(_String.Effect, "m2", true); }
        public static void jypk130up_by(GameState client) { client.Entity.Update(_String.Effect, "jypk130up_by", true); }
        public static void RideMatchArrive(GameState client) { client.Entity.Update(_String.Effect, "RideMatchArrive", true); }
        public static void istabhit_dis(GameState client) { client.Entity.Update(_String.Effect, "istabhit_dis", true); }
        public static void pkjinj_ll5(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_ll5", true); }
        public static void white_flower_full(GameState client) { client.Entity.Update(_String.Effect, "white-flower-full", true); }
        public static void istabind(GameState client) { client.Entity.Update(_String.Effect, "istabind", true); }
        public static void pkjinj_lr1(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_lr1", true); }
        public static void white_flower_g_1(GameState client) { client.Entity.Update(_String.Effect, "white-flower-g-1", true); }
        public static void jinshi(GameState client) { client.Entity.Update(_String.Effect, "jinshi", true); }
        public static void pkjinj_lr2(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_lr2", true); }
        public static void white_flower_rain(GameState client) { client.Entity.Update(_String.Effect, "white-flower-rain", true); }
        public static void jsb_1eddy_hit(GameState client) { client.Entity.Update(_String.Effect, "jsb_1eddy_hit", true); }
        public static void pkjinj_lr3(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_lr3", true); }
        public static void windupatt907(GameState client) { client.Entity.Update(_String.Effect, "windupatt907", true); }
        public static void jsb_1eddy_zan(GameState client) { client.Entity.Update(_String.Effect, "jsb_1eddy_zan", true); }
        public static void pkjinj_lr4(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_lr4", true); }
        public static void winnlock1(GameState client) { client.Entity.Update(_String.Effect, "winnlock1", true); }
        public static void jsb_gst01_app(GameState client) { client.Entity.Update(_String.Effect, "jsb_gst01_app", true); }
        public static void pkjinj_lr5(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_lr5", true); }
        public static void winnlock2(GameState client) { client.Entity.Update(_String.Effect, "winnlock2", true); }
        public static void jsb_gst01_cyc(GameState client) { client.Entity.Update(_String.Effect, "jsb_gst01_cyc", true); }
        public static void pkjinj_xl1(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_xl1", true); }
        public static void worryatt401(GameState client) { client.Entity.Update(_String.Effect, "worryatt401", true); }
        public static void jsb_gst01_dis(GameState client) { client.Entity.Update(_String.Effect, "jsb_gst01_dis", true); }
        public static void property_fire(GameState client) { client.Entity.Update(_String.Effect, "property_fire", true); }
        public static void ws_ffwys_fire(GameState client) { client.Entity.Update(_String.Effect, "ws_ffwys_fire", true); }
        public static void jsb_gst02_app(GameState client) { client.Entity.Update(_String.Effect, "jsb_gst02_app", true); }
        public static void property_gold(GameState client) { client.Entity.Update(_String.Effect, "property_gold", true); }
        public static void ws_ffwys_hand01(GameState client) { client.Entity.Update(_String.Effect, "ws_ffwys_hand01", true); }
        public static void jsb_gst02_cyc(GameState client) { client.Entity.Update(_String.Effect, "jsb_gst02_cyc", true); }
        public static void property_soil(GameState client) { client.Entity.Update(_String.Effect, "property_soil", true); }
        public static void ws_ffwys_hand02(GameState client) { client.Entity.Update(_String.Effect, "ws_ffwys_hand02", true); }
        public static void jsb_gst02_dis(GameState client) { client.Entity.Update(_String.Effect, "jsb_gst02_dis", true); }
        public static void property_water(GameState client) { client.Entity.Update(_String.Effect, "property_water", true); }
        public static void ws_ffwys_ploy(GameState client) { client.Entity.Update(_String.Effect, "ws_ffwys_ploy", true); }
        public static void iFrankohg_cyc(GameState client) { client.Entity.Update(_String.Effect, "iFrankohg_cyc", true); }
        public static void pk_ble_bea(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_bea", true); }
        public static void warflagsubmit(GameState client) { client.Entity.Update(_String.Effect, "warflagsubmit", true); }
        public static void iFrankohg_dis(GameState client) { client.Entity.Update(_String.Effect, "iFrankohg_dis", true); }
        public static void pk_ble_bow(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_bow", true); }
        public static void warriorpk_eight(GameState client) { client.Entity.Update(_String.Effect, "warriorpk_eight", true); }
        public static void iboss_attack(GameState client) { client.Entity.Update(_String.Effect, "iboss_attack", true); }
        public static void pk_ble_fie(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_fie", true); }
        public static void warriorpk_second(GameState client) { client.Entity.Update(_String.Effect, "warriorpk_second", true); }
        public static void iboss_claw401(GameState client) { client.Entity.Update(_String.Effect, "iboss_claw401", true); }
        public static void pk_ble_fla(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_fla", true); }
        public static void warriorpk_third(GameState client) { client.Entity.Update(_String.Effect, "warriorpk_third", true); }
        public static void iboss_fleghit(GameState client) { client.Entity.Update(_String.Effect, "iboss_fleghit", true); }
        public static void pk_ble_pir(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_pir", true); }
        public static void waterpk_eight(GameState client) { client.Entity.Update(_String.Effect, "waterpk_eight", true); }
        public static void iboss_ibutfly(GameState client) { client.Entity.Update(_String.Effect, "iboss_ibutfly", true); }
        public static void pk_ble_sol(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_sol", true); }
        public static void waterpk_second(GameState client) { client.Entity.Update(_String.Effect, "waterpk_second", true); }
        public static void iboss_ibuthit(GameState client) { client.Entity.Update(_String.Effect, "iboss_ibuthit", true); }
        public static void pk_ble_war(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_war", true); }
        public static void waterpk_third(GameState client) { client.Entity.Update(_String.Effect, "waterpk_third", true); }
        public static void improveSuc(GameState client) { client.Entity.Update(_String.Effect, "improveSuc", true); }
        public static void pk_ble_wat(GameState client) { client.Entity.Update(_String.Effect, "pk_ble_wat", true); }
        public static void wbonze_fire(GameState client) { client.Entity.Update(_String.Effect, "wbonze_fire", true); }
        public static void isallyf_app(GameState client) { client.Entity.Update(_String.Effect, "isallyf_app", true); }
        public static void pk_dra_ble(GameState client) { client.Entity.Update(_String.Effect, "pk_dra_ble", true); }
        public static void wbonze_state(GameState client) { client.Entity.Update(_String.Effect, "wbonze_state", true); }
        public static void isallyf_cyc(GameState client) { client.Entity.Update(_String.Effect, "isallyf_cyc", true); }
        public static void PK_resources(GameState client) { client.Entity.Update(_String.Effect, "PK_resources", true); }
        public static void weekpk_eight(GameState client) { client.Entity.Update(_String.Effect, "weekpk_eight", true); }
        public static void isallyf_dis(GameState client) { client.Entity.Update(_String.Effect, "isallyf_dis", true); }
        public static void PKchampion(GameState client) { client.Entity.Update(_String.Effect, "PKchampion", true); }
        public static void weekpk_second(GameState client) { client.Entity.Update(_String.Effect, "weekpk_second", true); }
        public static void isallyhit(GameState client) { client.Entity.Update(_String.Effect, "isallyhit", true); }
        public static void pkjinj_ll1(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_ll1", true); }
        public static void weekpk_third(GameState client) { client.Entity.Update(_String.Effect, "weekpk_third", true); }
        public static void isallyind(GameState client) { client.Entity.Update(_String.Effect, "isallyind", true); }
        public static void pkjinj_ll2(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_ll2", true); }
        public static void white_flower_char(GameState client) { client.Entity.Update(_String.Effect, "white-flower-char", true); }
        public static void istabhit_app(GameState client) { client.Entity.Update(_String.Effect, "istabhit_app", true); }
        public static void pkjinj_ll3(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_ll3", true); }
        public static void istabhit_cyc(GameState client) { client.Entity.Update(_String.Effect, "istabhit_cyc", true); }
        public static void pkjinj_ll4(GameState client) { client.Entity.Update(_String.Effect, "pkjinj_ll4", true); }
        public static void havefit(GameState client) { client.Entity.Update(_String.Effect, "havefit", true); }
        public static void hideperson(GameState client) { client.Entity.Update(_String.Effect, "hideperson", true); }
        public static void hot_goods_tips(GameState client) { client.Entity.Update(_String.Effect, "hot_goods_tips", true); }
        public static void iFranko_915(GameState client) { client.Entity.Update(_String.Effect, "iFranko_915", true); }
        public static void iFranko_916(GameState client) { client.Entity.Update(_String.Effect, "iFranko_916", true); }
        public static void iFranko_917(GameState client) { client.Entity.Update(_String.Effect, "iFranko_917", true); }
        public static void iFrankohg_app(GameState client) { client.Entity.Update(_String.Effect, "iFrankohg_app", true); }
        public static void get_special_dancer(GameState client) { client.Entity.Update(_String.Effect, "get_special_dancer", true); }
        public static void GetAchi(GameState client) { client.Entity.Update(_String.Effect, "GetAchi", true); }
        public static void girlassist_fir(GameState client) { client.Entity.Update(_String.Effect, "girlassist_fir", true); }
        public static void girlassist_sec(GameState client) { client.Entity.Update(_String.Effect, "girlassist_sec", true); }
        public static void girlassist_thi(GameState client) { client.Entity.Update(_String.Effect, "girlassist_thi", true); }
        public static void god_buj1(GameState client) { client.Entity.Update(_String.Effect, "god_buj1", true); }
        public static void god_buj2(GameState client) { client.Entity.Update(_String.Effect, "god_buj2", true); }
        public static void frost_end(GameState client) { client.Entity.Update(_String.Effect, "frost_end", true); }
        public static void gam_acc(GameState client) { client.Entity.Update(_String.Effect, "gam_acc", true); }
        public static void gam_buss(GameState client) { client.Entity.Update(_String.Effect, "gam_buss", true); }
        public static void gam_buss_ap(GameState client) { client.Entity.Update(_String.Effect, "gam_buss_ap", true); }
        public static void gam_buss_cyc(GameState client) { client.Entity.Update(_String.Effect, "gam_buss_cyc", true); }
        public static void gam_buss_end(GameState client) { client.Entity.Update(_String.Effect, "gam_buss_end", true); }
        public static void gam_cuddle_ap(GameState client) { client.Entity.Update(_String.Effect, "gam_cuddle_ap", true); }
        public static void factionbul_input(GameState client) { client.Entity.Update(_String.Effect, "factionbul_input", true); }
        public static void factionbul_succ(GameState client) { client.Entity.Update(_String.Effect, "factionbul_succ", true); }
        public static void fam_exp(GameState client) { client.Entity.Update(_String.Effect, "fam_exp", true); }
        public static void fam_exp_special(GameState client) { client.Entity.Update(_String.Effect, "fam_exp_special", true); }
        public static void fam_gain(GameState client) { client.Entity.Update(_String.Effect, "fam_gain", true); }
        public static void fam_gain_special(GameState client) { client.Entity.Update(_String.Effect, "fam_gain_special", true); }
        public static void fanpcse(GameState client) { client.Entity.Update(_String.Effect, "fanpcse", true); }
        public static void dealfly1(GameState client) { client.Entity.Update(_String.Effect, "dealfly1", true); }
        public static void dealfly2(GameState client) { client.Entity.Update(_String.Effect, "dealfly2", true); }
        public static void dealfly3(GameState client) { client.Entity.Update(_String.Effect, "dealfly3", true); }
        public static void dealfly4(GameState client) { client.Entity.Update(_String.Effect, "dealfly4", true); }
        public static void dealfly5(GameState client) { client.Entity.Update(_String.Effect, "dealfly5", true); }
        public static void dealfly6(GameState client) { client.Entity.Update(_String.Effect, "dealfly6", true); }
        public static void dealfly7(GameState client) { client.Entity.Update(_String.Effect, "dealfly7", true); }
        public static void gamebow(GameState client) { client.Entity.Update(_String.Effect, "gamebow", true); }
        public static void halo_huo_fir(GameState client) { client.Entity.Update(_String.Effect, "halo_huo_fir", true); }
        #endregion





    }
}
